exception.py[2018-06-06 10:54:16][ERROR]：Internal Server Error: /tj/
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Tools\Carry\mysite\views.py", line 466, in tongji
    res_size = len(_res)
NameError: name '_res' is not defined
HSD.py[2018-06-06 12:05:40][ERROR]：文件 HSD.py 第1045行报错：'2018-03-06' is not in list
HSD.py[2018-06-06 12:06:49][ERROR]：文件 HSD.py 第1045行报错：'2018-03-06' is not in list
HSD.py[2018-06-06 12:13:26][ERROR]：文件 HSD.py 第1045行报错：'2018-03-06' is not in list
base.py[2018-06-06 18:22:50][WARNING]：Not Found: /favicon.ico
base.py[2018-06-07 11:33:25][WARNING]：Not Found: /favicon.ico
exception.py[2018-06-11 10:03:13][ERROR]：Internal Server Error: /tj/
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Tools\Carry\mysite\views.py", line 540, in tongji
    return render(rq, 'tongji.html', locals())
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\defaulttags.py", line 969, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 565, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 28: 'static', expected 'elif'，'else' or 'endif'. Did you forget to register or load this tag?
base.py[2018-06-11 10:03:13][WARNING]：Not Found: /favicon.ico
views.py[2018-06-11 11:40:23][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:40:27][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:42:47][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:42:51][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:42:56][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:51:34][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:53:53][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:53:57][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:54:01][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:54:02][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:55:42][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:55:43][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:56:49][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:56:51][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:57:37][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:58:55][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 11:59:34][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 12:01:12][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 12:01:31][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 12:01:55][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 12:02:25][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-11 12:02:53][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
base.py[2018-06-11 13:32:31][WARNING]：Not Found: /favicon.ico
exception.py[2018-06-11 13:38:18][ERROR]：Internal Server Error: /tj/
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Tools\Carry\mysite\views.py", line 540, in tongji
    return render(rq, 'tongji.html', locals())
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 61: 'static'. Did you forget to register or load this tag?
views.py[2018-06-11 14:09:23][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
exception.py[2018-06-11 15:40:40][ERROR]：Internal Server Error: /tj/
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Tools\Carry\mysite\views.py", line 540, in tongji
    return render(rq, 'tongji.html', locals())
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 43: 'static'. Did you forget to register or load this tag?
base.py[2018-06-11 17:28:27][WARNING]：Not Found: /favicon.ico
HSD.py[2018-06-11 17:33:26][ERROR]：文件 HSD.py 第1043行报错：division by zero
HSD.py[2018-06-11 17:34:11][ERROR]：文件 HSD.py 第1043行报错：division by zero
views.py[2018-06-12 11:06:18][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:14:46][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:15:12][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:15:42][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:16:21][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:16:26][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:45:06][ERROR]：文件：views.py 第936行报错： sequence index must be integer, not 'slice'
views.py[2018-06-12 11:45:40][ERROR]：文件：views.py 第936行报错： '9'
views.py[2018-06-12 11:46:39][ERROR]：文件：views.py 第936行报错： '9'
views.py[2018-06-12 11:50:12][ERROR]：文件：views.py 第936行报错： '9'
views.py[2018-06-12 12:03:28][ERROR]：文件：views.py 第998行报错： sequence index must be integer, not 'slice'
exception.py[2018-06-12 12:03:28][ERROR]：Internal Server Error: /hc/
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\django-1.11.8-py3.6.egg\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Tools\Carry\mysite\views.py", line 1000, in huice
    return render(rq, 'hc.html', {'hc': hc, 'huizong': huizong, 'fa': fa})
UnboundLocalError: local variable 'hc' referenced before assignment
base.py[2018-06-12 12:03:29][WARNING]：Not Found: /favicon.ico
base.py[2018-06-12 12:03:29][WARNING]：Not Found: /favicon.ico
HSD.py[2018-06-12 17:53:22][ERROR]：文件 HSD.py 第1043行报错：'2018-03-06' is not in list
HSD.py[2018-06-12 17:53:56][ERROR]：文件 HSD.py 第1043行报错：'2018-03-06' is not in list
